//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Entities
{
    using System;

    public partial class MpiEquityChars_Test
    {
        public string ProductId { get; set; }
        public DateTime PeriodEnding { get; set; }
        public double? FiveYearDividendGrowth { get; set; }
        public double? FiveYearEPSGrowth { get; set; }
        public double? BookToPrice { get; set; }
        public double? DebtToEquity { get; set; }
        public double? EarningsToPrice { get; set; }
        public double? EquityBeta { get; set; }
        public double? EquityRSquared { get; set; }
        public double? EquityYield { get; set; }
        public double? NumberOfstocks { get; set; }
        public double? PriceToBook { get; set; }
        public double? PriceToEarnings { get; set; }
        public double? PriceToSales { get; set; }
        public double? Turnover { get; set; }
        public double? ReturnOnEquity { get; set; }
        public double? WilshireSizeScore { get; set; }
        public double? WilshireStyleScore { get; set; }
        public double? Percentcash { get; set; }
        public double? Forward5YearEPSGrowth { get; set; }
        public double? ForwardPE { get; set; }
        public double? wtdAvgMarketCap { get; set; }
        public double? MedianMarketCap { get; set; }
        public double? PriceToCashFlow { get; set; }
        public DateTime? LastHoldingsDate { get; set; }
        public double? Hist3YrSalesGrowth { get; set; }
        public double? fHist3YrEPSGrowth { get; set; }
        public double? C52WeekReturn { get; set; }
        public double? ROA { get; set; }
    
        public virtual MpiHeader_Test MpiHeader_Test { get; set; }
    }
}
