//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpiFixedIncomeChars_Test
    {
        public string ProductID { get; set; }
        public System.DateTime PeriodEnding { get; set; }
        public Nullable<double> A { get; set; }
        public Nullable<double> AA { get; set; }
        public Nullable<double> AAA { get; set; }
        public string AverageQuality { get; set; }
        public Nullable<double> B { get; set; }
        public Nullable<double> BB { get; set; }
        public Nullable<double> BBB { get; set; }
        public Nullable<double> LessB { get; set; }
        public Nullable<double> Govt { get; set; }
        public Nullable<double> NR { get; set; }
        public Nullable<double> NumberofBonds { get; set; }
        public Nullable<double> NumberofStocks { get; set; }
        public Nullable<double> TurnOver { get; set; }
        public Nullable<double> YieldtoMaturity { get; set; }
        public Nullable<double> DurMore10 { get; set; }
        public Nullable<double> DurLess1 { get; set; }
        public Nullable<double> DurLess10 { get; set; }
        public Nullable<double> DurLess2 { get; set; }
        public Nullable<double> DurLess3 { get; set; }
        public Nullable<double> DurLess4 { get; set; }
        public Nullable<double> DurLess5 { get; set; }
        public Nullable<double> DurLess6 { get; set; }
        public Nullable<double> DurLess7 { get; set; }
        public Nullable<double> DurLess8 { get; set; }
        public Nullable<double> DurLess9 { get; set; }
        public Nullable<double> DurationEffective { get; set; }
        public Nullable<double> AvgQuality { get; set; }
        public Nullable<double> Convexity { get; set; }
    
        public virtual MpiHeader_Test MpiHeader_Test { get; set; }
    }
}
