//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Entities
{

    public partial class MpiReturns_Test
    {
        public string Code { get; set; }
        public string Rtndate { get; set; }
        public double? Rtnvalue { get; set; }
    
        public virtual MpiHeader_Test MpiHeader_Test { get; set; }
    }
}
