//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAssetClass
    {
        public double AssetID { get; set; }
        public string AssetName { get; set; }
        public string BenchmarkID { get; set; }
        public string BenchmarkShortName { get; set; }
        public string UniverseID { get; set; }
        public string UniverseName { get; set; }
        public string AssetClassCurrentCoverage { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
